pipeline {
     agent any

     stages {
          stage("Unit test") {
               steps {
                    dir("Chapter08/sample1") {
                         sh "./gradlew test"
                    }
               }
          }

          stage("Code coverage") {
               steps {
                    dir("Chapter08/sample1") {
                         sh "./gradlew clean test jacocoTestReport jacocoTestCoverageVerification"
                    }
               }
          }

          stage("Static code analysis") {
               steps {
                    dir("Chapter08/sample1") {
                         sh "./gradlew checkstyleMain"
                    }
               }
          }

          stage("jacoco checkstyle") {
               steps {
                    dir("Chapter08/sample1") {
                         sh "./gradlew checkstyleTest"
                    }
               }
               post {
                    always {
                         publishHTML(target: [
                              reportDir: "Chapter08/sample1/build/reports/checkstyle",
                              reportFiles: "test.html",
                              reportName: "jacoco checkstyle"
                         ])
                    }
               }
          }
     }
}