stage("Unit test") {
     steps {
          dir("Chapter08/sample1") {
               sh "./gradlew test"
          }
     }
}

stage("Code coverage") {
     steps {
          dir("Chapter08/sample1") {
               sh "./gradlew clean test jacocoTestReport jacocoTestCoverageVerification"
          }
     }
}

stage("Static code analysis") {
     steps {
          dir("Chapter08/sample1") {
               sh "./gradlew checkstyleMain"
          }
     }
}